### ISSUE TITLE
배경음악 배속 기능 추가

### ISSUE THREAD

**Issue by heesue-coder** [CSID-DGU/2020-2-OSSP-CP-17woljang-9#13]
PVP모드로 게임할 시, 레벨이 높은 플레이어 기준으로 배경음악이 빨라지는 기능 추가해야합니다!

**Comment by c2lv** [comment]
[WAV 파일 읽고 쓰기](https://docs.python.org/ko/3/library/wave.html)
[pygame audio playback speed](https://stackoverrun.com/ko/q/442764)
https://stackoverflow.com/questions/47732657/wave-error-channels-not-specified
https://stackoverrun.com/ko/q/6228618

**Comment by RoJooHee** [comment]
현준님 풀리를 제껄로 합쳐서 머지시켰기때문에   현준님 풀리를 close 했는데,
저 close 된 거에 배속기능이 포함되어있어서
이 이슈는 완성되었기에 닫겠습니당
