### ISSUE TITLE
로그인 기능 추가

### ISSUE THREAD

**Issue by c2lv** [CSID-DGU/2020-2-OSSP-CP-17woljang-9#2]
[loginTest.zip](https://github.com/CSID-DGU/2020-2-OSSP-CP-17woljang-9/files/5487289/loginTest.2.zip)

추가/수정 필요한 것들 주석 달아서 압축파일로 첨부합니다!
코드들 참고해서 아예 새로 만들어도 될 것 같아요.
2번 파일 코드는 동작이 안 돼서 도움 요청합니다 ;-;
주석 보시고 다른 추가/수정/삭제 사항 있으면 알려주세요!

어떤 것 추가하고 수정하고 삭제해야 하는 지 계속 이슈 업데이트!

**업데이트 사항**
* 압축 파일에 예시 하나 추가

**Comment by RoJooHee** [comment]
아이디나 비밀번호 잘못 입력했을 때 일단 계속 다시 로그인 페이지로 돌아가도록 했습니다.
회원가입 때 중복된 아이디는 재입력 하게 했습니다. 비밀번호 보안검사까지 할정도로 비밀번호를 길게 안쓸 듯 해서 일단 이건 안했습니다
로그인과 회원가입 선택시 다른값 입력하면 다시 입력못하는 거 수정했습니다. 변수명이랑 함수명이 같으면 안돼요! (start()로 함수명 바꿨습니당)

**저번에 올렸던것 정리하면서 여기에 다시 올립니다
[login2.zip](https://github.com/CSID-DGU/2020-2-OSSP-CP-17woljang-9/files/5590320/login2.zip)

**Comment by RoJooHee** [comment]
저희가 로그인기능은 처음부터 우선순위에 두지는 않았기에 클로즈 하겠습니다.
개발하고있는 콘텐츠와 버그정리, 창크기 조절에 집중해서 마무리합시다!
