### ISSUE TITLE
디버그 모드 구현(다양한 변수 조작 가능)

### ISSUE THREAD

**Issue by RoJooHee** [CSID-DGU/2020-2-OSSP-CP-17woljang-9#22]
블록 떨어지는 속도, 배경음악 속도, 블록, 아이템 무제한 등
다양한 변수들에 대해 조작하고 테스트할 수 있는 모드를 구현합니다!

**Comment by c2lv** [comment]
디버그 모드가 구현되어 이슈를 닫겠습니다~
