### ISSUE TITLE
#2 에 대해 1번 코드 주석부문 구현

### ISSUE THREAD

**Issue by RoJooHee** [CSID-DGU/2020-2-OSSP-CP-17woljang-9#3]
1. 아이디나 비밀번호 잘못 입력했을 때 일단 계속 다시 로그인 페이지로 돌아가도록 했습니다.
2. 회원가입 때 중복된 아이디는 재입력 하게 했습니다. 비밀번호 보안검사까지 할정도로 비밀번호를 길게 안쓸 듯 해서 일단 이건 안했습니다
3. 로그인과 회원가입 선택시 다른값 입력하면 다시 입력못하는 거 수정했습니다. 변수명이랑 함수명이 같으면 안돼요! (start()로 함수명 바꿨습니당)[

[login2.zip](https://github.com/CSID-DGU/2020-2-OSSP-CP-17woljang-9/files/5488126/login2.zip)

**Comment by c2lv** [comment]
오 감사합니다 확인해볼게요!
이슈는 너무 많으면 헷갈릴 수 있어서 이런 경우에는 새로 이슈를 만들지 않고
해당하는 이슈에 Comment로 남겨주시면 더 좋을 것 같아요!
나중에 이렇게 압축된 파일이 아닌 깃허브에 직접 코드 올리면서 자연스레 해결될 문제긴 합니다 ㅎ.ㅎ

**Comment by RoJooHee** [comment]
오! comment에 파일 못올리는 줄 알았는데 가능하네요!! 넹 얼른 코드를 직접 올려봅시다 ㅎㅎ
