### ISSUE TITLE
타임 어택 모드 구현

### ISSUE THREAD

**Issue by c2lv** [CSID-DGU/2020-2-OSSP-CP-17woljang-9#47]
주어진 시간이 끝나면 게임 오버가 되는 타임 어택 모드를 구현합니다.

**Comment by c2lv** [comment]
https://blog.naver.com/trudiaa/221973644998

**Comment by RoJooHee** [comment]
언제 오류가 생겼는지는 모르겠지만, 타임어택모드에서 종료화면 먼저 시작하고 넘겨야 게임화면 시작하는 버그 수정했습니다!
